name: uchicago_12h
on:
    schedule:
        - cron: "3 3,15 * * *"

permissions:
    contents: read

jobs:
    hepspec:
        runs-on: arc-runner-set-uchicago-alarm-alert-system
        steps:
            - uses: actions/checkout@v6
            - name: execute
              run: ./hepspec.sh
              shell: bash
              env:
                  ES_HOST: ${{ secrets.ES_HOST }}
                  HEPSPEC_ES_USER: ${{ secrets.HEPSPEC_ES_USER }}
                  HEPSPEC_ES_PASS: ${{ secrets.HEPSPEC_ES_PASS }}
                  HEPSPEC_TOKEN: ${{ secrets.HEPSPEC_TOKEN }}
                  AAAS: ${{ secrets.AAAS }}
                  MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
            - name: upload log
              if: always()
              uses: actions/upload-artifact@v5
              with:
                  name: ${{ github.job }}-logs
                  path: |
                      hepspec.log
