name: uchicago_24h
on:
    schedule:
        - cron: "5 2 * * *"

permissions:
    contents: read

jobs:
    hepspec:
        runs-on: arc-runner-set-uchicago-alarm-alert-system
        steps:
            - uses: actions/checkout@v6
            - name: execute
              run: ./fts-aggregator.sh
              shell: bash
              env:
                  ES_HOST: ${{ secrets.ES_HOST }}
                  HEPSPEC_ES_USER: ${{ secrets.ES_USER }}
                  HEPSPEC_ES_PASS: ${{ secrets.ES_PASS }}
            - name: upload log
              if: always()
              uses: actions/upload-artifact@v6
              with:
                  name: ${{ github.job }}-logs
                  path: |
                      fts-aggregator.log
